package fm.castbox.mediation.helper;

import android.os.Build;
import com.applovin.sdk.AppLovinErrorCodes;
import com.google.android.gms.ads.RequestConfiguration;
import com.ironsource.mediationsdk.logger.IronSourceError;
import com.ironsource.mediationsdk.utils.IronSourceConstants;
import java.time.ZoneId;
import java.util.HashMap;
import java.util.TimeZone;
import ms.bd.o.Pgl.c;

/* loaded from: classes3.dex */
public class TimezoneInfoProvider {
    private HashMap<String, TimezoneInfo> countries;
    private String zoneId = getZoneId();

    /* loaded from: classes3.dex */
    public static class TimezoneInfo {
        private final String continentCode;
        private final String continentName;
        private final String countryCode;
        private final String countryName;
        private final int rawOffsetInMinutes;
        private final String timezone;

        public TimezoneInfo(String str, String str2, String str3, String str4, String str5, int i10) {
            this.timezone = str;
            this.continentCode = str2;
            this.continentName = str3;
            this.countryCode = str4;
            this.countryName = str5;
            this.rawOffsetInMinutes = i10;
        }

        public String getContinentCode() {
            return this.continentCode;
        }

        public String getContinentName() {
            return this.continentName;
        }

        public String getCountryCode() {
            return this.countryCode;
        }

        public String getCountryName() {
            return this.countryName;
        }

        public int getRawOffsetInMinutes() {
            return this.rawOffsetInMinutes;
        }

        public String getTimezone() {
            return this.timezone;
        }

        public String toString() {
            return "TimezoneInfo{timezone='" + this.timezone + "', continentCode='" + this.continentCode + "', continentName='" + this.continentName + "', countryCode='" + this.countryCode + "', countryName='" + this.countryName + "', rawOffsetInMinutes=" + this.rawOffsetInMinutes + '}';
        }
    }

    public TimezoneInfoProvider() {
        this.countries = null;
        this.countries = null;
    }

    private String getZoneId() {
        try {
            if (Build.VERSION.SDK_INT < 26) {
                return TimeZone.getDefault().getID();
            }
            return ZoneId.systemDefault().getId();
        } catch (Exception unused) {
            return null;
        }
    }

    private synchronized void initCountries() {
        HashMap<String, TimezoneInfo> hashMap = new HashMap<>();
        this.countries = hashMap;
        hashMap.put("Pacific/Niue".toLowerCase(), new TimezoneInfo("Pacific/Niue", "OC", "Oceania", "NU", "Niue", -660));
        this.countries.put("Pacific/Midway".toLowerCase(), new TimezoneInfo("Pacific/Midway", "OC", "Oceania", "UM", "United States Minor Outlying Islands", -660));
        this.countries.put("Pacific/Pago_Pago".toLowerCase(), new TimezoneInfo("Pacific/Pago_Pago", "OC", "Oceania", "AS", "American Samoa", -660));
        this.countries.put("Pacific/Samoa".toLowerCase(), new TimezoneInfo("Pacific/Samoa", "OC", "Oceania", "AS", "American Samoa", -660));
        this.countries.put("US/Samoa".toLowerCase(), new TimezoneInfo("US/Samoa", "OC", "Oceania", "AS", "American Samoa", -660));
        this.countries.put("Pacific/Rarotonga".toLowerCase(), new TimezoneInfo("Pacific/Rarotonga", "OC", "Oceania", "CK", "Cook Islands", AppLovinErrorCodes.INCENTIVIZED_USER_CLOSED_VIDEO));
        this.countries.put("Pacific/Honolulu".toLowerCase(), new TimezoneInfo("Pacific/Honolulu", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_USER_CLOSED_VIDEO));
        this.countries.put("Pacific/Johnston".toLowerCase(), new TimezoneInfo("Pacific/Johnston", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_USER_CLOSED_VIDEO));
        this.countries.put("US/Hawaii".toLowerCase(), new TimezoneInfo("US/Hawaii", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_USER_CLOSED_VIDEO));
        this.countries.put("Pacific/Tahiti".toLowerCase(), new TimezoneInfo("Pacific/Tahiti", "OC", "Oceania", "PF", "French Polynesia", AppLovinErrorCodes.INCENTIVIZED_USER_CLOSED_VIDEO));
        this.countries.put("Pacific/Marquesas".toLowerCase(), new TimezoneInfo("Pacific/Marquesas", "OC", "Oceania", "PF", "French Polynesia", -570));
        this.countries.put("Pacific/Gambier".toLowerCase(), new TimezoneInfo("Pacific/Gambier", "OC", "Oceania", "PF", "French Polynesia", -540));
        this.countries.put("America/Adak".toLowerCase(), new TimezoneInfo("America/Adak", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_USER_CLOSED_VIDEO));
        this.countries.put("America/Atka".toLowerCase(), new TimezoneInfo("America/Atka", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_USER_CLOSED_VIDEO));
        this.countries.put("US/Aleutian".toLowerCase(), new TimezoneInfo("US/Aleutian", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_USER_CLOSED_VIDEO));
        this.countries.put("America/Anchorage".toLowerCase(), new TimezoneInfo("America/Anchorage", "NA", "North America", "US", "United States", -540));
        this.countries.put("America/Juneau".toLowerCase(), new TimezoneInfo("America/Juneau", "NA", "North America", "US", "United States", -540));
        this.countries.put("America/Metlakatla".toLowerCase(), new TimezoneInfo("America/Metlakatla", "NA", "North America", "US", "United States", -540));
        this.countries.put("America/Nome".toLowerCase(), new TimezoneInfo("America/Nome", "NA", "North America", "US", "United States", -540));
        this.countries.put("America/Sitka".toLowerCase(), new TimezoneInfo("America/Sitka", "NA", "North America", "US", "United States", -540));
        this.countries.put("America/Yakutat".toLowerCase(), new TimezoneInfo("America/Yakutat", "NA", "North America", "US", "United States", -540));
        this.countries.put("US/Alaska".toLowerCase(), new TimezoneInfo("US/Alaska", "NA", "North America", "US", "United States", -540));
        this.countries.put("Pacific/Pitcairn".toLowerCase(), new TimezoneInfo("Pacific/Pitcairn", "OC", "Oceania", "PN", "Pitcairn", -480));
        this.countries.put("America/Hermosillo".toLowerCase(), new TimezoneInfo("America/Hermosillo", "NA", "North America", "MX", "Mexico", -420));
        this.countries.put("America/Phoenix".toLowerCase(), new TimezoneInfo("America/Phoenix", "NA", "North America", "US", "United States", -420));
        this.countries.put("US/Arizona".toLowerCase(), new TimezoneInfo("US/Arizona", "NA", "North America", "US", "United States", -420));
        this.countries.put("America/Creston".toLowerCase(), new TimezoneInfo("America/Creston", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Los_Angeles".toLowerCase(), new TimezoneInfo("America/Los_Angeles", "NA", "North America", "US", "United States", -480));
        this.countries.put("US/Pacific".toLowerCase(), new TimezoneInfo("US/Pacific", "NA", "North America", "US", "United States", -480));
        this.countries.put("America/Tijuana".toLowerCase(), new TimezoneInfo("America/Tijuana", "NA", "North America", "MX", "Mexico", -480));
        this.countries.put("America/Ensenada".toLowerCase(), new TimezoneInfo("America/Ensenada", "NA", "North America", "MX", "Mexico", -480));
        this.countries.put("America/Santa_Isabel".toLowerCase(), new TimezoneInfo("America/Santa_Isabel", "NA", "North America", "MX", "Mexico", -480));
        this.countries.put("Mexico/BajaNorte".toLowerCase(), new TimezoneInfo("Mexico/BajaNorte", "NA", "North America", "MX", "Mexico", -480));
        this.countries.put("America/Vancouver".toLowerCase(), new TimezoneInfo("America/Vancouver", "NA", "North America", "CA", "Canada", -480));
        this.countries.put("Canada/Pacific".toLowerCase(), new TimezoneInfo("Canada/Pacific", "NA", "North America", "CA", "Canada", -480));
        this.countries.put("America/Dawson".toLowerCase(), new TimezoneInfo("America/Dawson", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Dawson_Creek".toLowerCase(), new TimezoneInfo("America/Dawson_Creek", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Fort_Nelson".toLowerCase(), new TimezoneInfo("America/Fort_Nelson", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Whitehorse".toLowerCase(), new TimezoneInfo("America/Whitehorse", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("Canada/Yukon".toLowerCase(), new TimezoneInfo("Canada/Yukon", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Belize".toLowerCase(), new TimezoneInfo("America/Belize", "NA", "North America", "BZ", "Belize", -360));
        this.countries.put("America/Guatemala".toLowerCase(), new TimezoneInfo("America/Guatemala", "NA", "North America", "GT", "Guatemala", -360));
        this.countries.put("America/Managua".toLowerCase(), new TimezoneInfo("America/Managua", "NA", "North America", "NI", "Nicaragua", -360));
        this.countries.put("America/Costa_Rica".toLowerCase(), new TimezoneInfo("America/Costa_Rica", "NA", "North America", "CR", "Costa Rica", -360));
        this.countries.put("America/El_Salvador".toLowerCase(), new TimezoneInfo("America/El_Salvador", "NA", "North America", "SV", "El Salvador", -360));
        this.countries.put("America/Regina".toLowerCase(), new TimezoneInfo("America/Regina", "NA", "North America", "CA", "Canada", -360));
        this.countries.put("America/Swift_Current".toLowerCase(), new TimezoneInfo("America/Swift_Current", "NA", "North America", "CA", "Canada", -360));
        this.countries.put("Canada/Saskatchewan".toLowerCase(), new TimezoneInfo("Canada/Saskatchewan", "NA", "North America", "CA", "Canada", -360));
        this.countries.put("America/Tegucigalpa".toLowerCase(), new TimezoneInfo("America/Tegucigalpa", "NA", "North America", "HN", "Honduras", -360));
        this.countries.put("Pacific/Galapagos".toLowerCase(), new TimezoneInfo("Pacific/Galapagos", "SA", "South America", "EC", "Ecuador", -360));
        this.countries.put("America/Cambridge_Bay".toLowerCase(), new TimezoneInfo("America/Cambridge_Bay", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Edmonton".toLowerCase(), new TimezoneInfo("America/Edmonton", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Inuvik".toLowerCase(), new TimezoneInfo("America/Inuvik", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Yellowknife".toLowerCase(), new TimezoneInfo("America/Yellowknife", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("Canada/Mountain".toLowerCase(), new TimezoneInfo("Canada/Mountain", "NA", "North America", "CA", "Canada", -420));
        this.countries.put("America/Chihuahua".toLowerCase(), new TimezoneInfo("America/Chihuahua", "NA", "North America", "MX", "Mexico", -420));
        this.countries.put("America/Mazatlan".toLowerCase(), new TimezoneInfo("America/Mazatlan", "NA", "North America", "MX", "Mexico", -420));
        this.countries.put("America/Ojinaga".toLowerCase(), new TimezoneInfo("America/Ojinaga", "NA", "North America", "MX", "Mexico", -420));
        this.countries.put("Mexico/BajaSur".toLowerCase(), new TimezoneInfo("Mexico/BajaSur", "NA", "North America", "MX", "Mexico", -420));
        this.countries.put("America/Boise".toLowerCase(), new TimezoneInfo("America/Boise", "NA", "North America", "US", "United States", -420));
        this.countries.put("America/Denver".toLowerCase(), new TimezoneInfo("America/Denver", "NA", "North America", "US", "United States", -420));
        this.countries.put("America/Shiprock".toLowerCase(), new TimezoneInfo("America/Shiprock", "NA", "North America", "US", "United States", -420));
        this.countries.put("Navajo".toLowerCase(), new TimezoneInfo("Navajo", "NA", "North America", "US", "United States", -420));
        this.countries.put("US/Mountain".toLowerCase(), new TimezoneInfo("US/Mountain", "NA", "North America", "US", "United States", -420));
        this.countries.put("America/Eirunepe".toLowerCase(), new TimezoneInfo("America/Eirunepe", "SA", "South America", "BR", "Brazil", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Rio_Branco".toLowerCase(), new TimezoneInfo("America/Rio_Branco", "SA", "South America", "BR", "Brazil", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Porto_Acre".toLowerCase(), new TimezoneInfo("America/Porto_Acre", "SA", "South America", "BR", "Brazil", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("Brazil/Acre".toLowerCase(), new TimezoneInfo("Brazil/Acre", "SA", "South America", "BR", "Brazil", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Chicago".toLowerCase(), new TimezoneInfo("America/Chicago", "NA", "North America", "US", "United States", -360));
        this.countries.put("America/Indiana/Knox".toLowerCase(), new TimezoneInfo("America/Indiana/Knox", "NA", "North America", "US", "United States", -360));
        this.countries.put("America/Indiana/Tell_City".toLowerCase(), new TimezoneInfo("America/Indiana/Tell_City", "NA", "North America", "US", "United States", -360));
        this.countries.put("America/Menominee".toLowerCase(), new TimezoneInfo("America/Menominee", "NA", "North America", "US", "United States", -360));
        this.countries.put("America/North_Dakota/Beulah".toLowerCase(), new TimezoneInfo("America/North_Dakota/Beulah", "NA", "North America", "US", "United States", -360));
        this.countries.put("America/North_Dakota/Center".toLowerCase(), new TimezoneInfo("America/North_Dakota/Center", "NA", "North America", "US", "United States", -360));
        this.countries.put("America/North_Dakota/New_Salem".toLowerCase(), new TimezoneInfo("America/North_Dakota/New_Salem", "NA", "North America", "US", "United States", -360));
        this.countries.put("US/Central".toLowerCase(), new TimezoneInfo("US/Central", "NA", "North America", "US", "United States", -360));
        this.countries.put("America/Knox_IN".toLowerCase(), new TimezoneInfo("America/Knox_IN", "NA", "North America", "US", "United States", -360));
        this.countries.put("US/Indiana-Starke".toLowerCase(), new TimezoneInfo("US/Indiana-Starke", "NA", "North America", "US", "United States", -360));
        this.countries.put("America/Bahia_Banderas".toLowerCase(), new TimezoneInfo("America/Bahia_Banderas", "NA", "North America", "MX", "Mexico", -360));
        this.countries.put("America/Matamoros".toLowerCase(), new TimezoneInfo("America/Matamoros", "NA", "North America", "MX", "Mexico", -360));
        this.countries.put("America/Merida".toLowerCase(), new TimezoneInfo("America/Merida", "NA", "North America", "MX", "Mexico", -360));
        this.countries.put("America/Mexico_City".toLowerCase(), new TimezoneInfo("America/Mexico_City", "NA", "North America", "MX", "Mexico", -360));
        this.countries.put("America/Monterrey".toLowerCase(), new TimezoneInfo("America/Monterrey", "NA", "North America", "MX", "Mexico", -360));
        this.countries.put("Mexico/General".toLowerCase(), new TimezoneInfo("Mexico/General", "NA", "North America", "MX", "Mexico", -360));
        this.countries.put("America/Rainy_River".toLowerCase(), new TimezoneInfo("America/Rainy_River", "NA", "North America", "CA", "Canada", -360));
        this.countries.put("America/Rankin_Inlet".toLowerCase(), new TimezoneInfo("America/Rankin_Inlet", "NA", "North America", "CA", "Canada", -360));
        this.countries.put("America/Resolute".toLowerCase(), new TimezoneInfo("America/Resolute", "NA", "North America", "CA", "Canada", -360));
        this.countries.put("America/Winnipeg".toLowerCase(), new TimezoneInfo("America/Winnipeg", "NA", "North America", "CA", "Canada", -360));
        this.countries.put("Canada/Central".toLowerCase(), new TimezoneInfo("Canada/Central", "NA", "North America", "CA", "Canada", -360));
        this.countries.put("America/Bogota".toLowerCase(), new TimezoneInfo("America/Bogota", "SA", "South America", "CO", "Colombia", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("Pacific/Easter".toLowerCase(), new TimezoneInfo("Pacific/Easter", "SA", "South America", "CL", "Chile", -360));
        this.countries.put("Chile/EasterIsland".toLowerCase(), new TimezoneInfo("Chile/EasterIsland", "SA", "South America", "CL", "Chile", -360));
        this.countries.put("America/Atikokan".toLowerCase(), new TimezoneInfo("America/Atikokan", "NA", "North America", "CA", "Canada", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Cancun".toLowerCase(), new TimezoneInfo("America/Cancun", "NA", "North America", "MX", "Mexico", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Cayman".toLowerCase(), new TimezoneInfo("America/Cayman", "NA", "North America", "KY", "Cayman Islands", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Jamaica".toLowerCase(), new TimezoneInfo("America/Jamaica", "NA", "North America", "JM", "Jamaica", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("Jamaica".toLowerCase(), new TimezoneInfo("Jamaica", "NA", "North America", "JM", "Jamaica", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Panama".toLowerCase(), new TimezoneInfo("America/Panama", "NA", "North America", "PA", "Panama", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Coral_Harbour".toLowerCase(), new TimezoneInfo("America/Coral_Harbour", "NA", "North America", "PA", "Panama", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Guayaquil".toLowerCase(), new TimezoneInfo("America/Guayaquil", "SA", "South America", "EC", "Ecuador", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Lima".toLowerCase(), new TimezoneInfo("America/Lima", "SA", "South America", "PE", "Peru", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Boa_Vista".toLowerCase(), new TimezoneInfo("America/Boa_Vista", "SA", "South America", "BR", "Brazil", -240));
        this.countries.put("America/Campo_Grande".toLowerCase(), new TimezoneInfo("America/Campo_Grande", "SA", "South America", "BR", "Brazil", -240));
        this.countries.put("America/Cuiaba".toLowerCase(), new TimezoneInfo("America/Cuiaba", "SA", "South America", "BR", "Brazil", -240));
        this.countries.put("America/Manaus".toLowerCase(), new TimezoneInfo("America/Manaus", "SA", "South America", "BR", "Brazil", -240));
        this.countries.put("America/Porto_Velho".toLowerCase(), new TimezoneInfo("America/Porto_Velho", "SA", "South America", "BR", "Brazil", -240));
        this.countries.put("Brazil/West".toLowerCase(), new TimezoneInfo("Brazil/West", "SA", "South America", "BR", "Brazil", -240));
        this.countries.put("America/St_Kitts".toLowerCase(), new TimezoneInfo("America/St_Kitts", "NA", "North America", "KN", "Saint Kitts and Nevis", -240));
        this.countries.put("America/Blanc-Sablon".toLowerCase(), new TimezoneInfo("America/Blanc-Sablon", "NA", "North America", "CA", "Canada", -240));
        this.countries.put("America/Montserrat".toLowerCase(), new TimezoneInfo("America/Montserrat", "NA", "North America", "MS", "Montserrat", -240));
        this.countries.put("America/Barbados".toLowerCase(), new TimezoneInfo("America/Barbados", "NA", "North America", "BB", "Barbados", -240));
        this.countries.put("America/St_Lucia".toLowerCase(), new TimezoneInfo("America/St_Lucia", "NA", "North America", "LC", "Saint Lucia", -240));
        this.countries.put("America/Port_of_Spain".toLowerCase(), new TimezoneInfo("America/Port_of_Spain", "NA", "North America", "TT", "Trinidad and Tobago", -240));
        this.countries.put("America/Martinique".toLowerCase(), new TimezoneInfo("America/Martinique", "NA", "North America", "MQ", "Martinique", -240));
        this.countries.put("America/St_Barthelemy".toLowerCase(), new TimezoneInfo("America/St_Barthelemy", "NA", "North America", "BL", "Saint Barthelemy", -240));
        this.countries.put("America/St_Vincent".toLowerCase(), new TimezoneInfo("America/St_Vincent", "NA", "North America", "VC", "Saint Vincent and the Grenadines", -240));
        this.countries.put("America/Kralendijk".toLowerCase(), new TimezoneInfo("America/Kralendijk", "NA", "North America", "BQ", "Bonaire, Saint Eustatius and Saba ", -240));
        this.countries.put("America/Guadeloupe".toLowerCase(), new TimezoneInfo("America/Guadeloupe", "NA", "North America", "GP", "Guadeloupe", -240));
        this.countries.put("America/Marigot".toLowerCase(), new TimezoneInfo("America/Marigot", "NA", "North America", "MF", "Saint Martin", -240));
        this.countries.put("America/Aruba".toLowerCase(), new TimezoneInfo("America/Aruba", "NA", "North America", "AW", "Aruba", -240));
        this.countries.put("America/Lower_Princes".toLowerCase(), new TimezoneInfo("America/Lower_Princes", "NA", "North America", "SX", "Sint Maarten", -240));
        this.countries.put("America/Tortola".toLowerCase(), new TimezoneInfo("America/Tortola", "NA", "North America", "VG", "British Virgin Islands", -240));
        this.countries.put("America/Dominica".toLowerCase(), new TimezoneInfo("America/Dominica", "NA", "North America", "DM", "Dominica", -240));
        this.countries.put("America/St_Thomas".toLowerCase(), new TimezoneInfo("America/St_Thomas", "NA", "North America", "VI", "U.S. Virgin Islands", -240));
        this.countries.put("America/Grenada".toLowerCase(), new TimezoneInfo("America/Grenada", "NA", "North America", "GD", "Grenada", -240));
        this.countries.put("America/Antigua".toLowerCase(), new TimezoneInfo("America/Antigua", "NA", "North America", "AG", "Antigua and Barbuda", -240));
        this.countries.put("America/Puerto_Rico".toLowerCase(), new TimezoneInfo("America/Puerto_Rico", "NA", "North America", "PR", "Puerto Rico", -240));
        this.countries.put("America/Virgin".toLowerCase(), new TimezoneInfo("America/Virgin", "NA", "North America", "PR", "Puerto Rico", -240));
        this.countries.put("America/Santo_Domingo".toLowerCase(), new TimezoneInfo("America/Santo_Domingo", "NA", "North America", "DO", "Dominican Republic", -240));
        this.countries.put("America/Anguilla".toLowerCase(), new TimezoneInfo("America/Anguilla", "NA", "North America", "AI", "Anguilla", -240));
        this.countries.put("America/Curacao".toLowerCase(), new TimezoneInfo("America/Curacao", "NA", "North America", "CW", "Curacao", -240));
        this.countries.put("America/La_Paz".toLowerCase(), new TimezoneInfo("America/La_Paz", "SA", "South America", "BO", "Bolivia", -240));
        this.countries.put("America/Havana".toLowerCase(), new TimezoneInfo("America/Havana", "NA", "North America", "CU", "Cuba", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("Cuba".toLowerCase(), new TimezoneInfo("Cuba", "NA", "North America", "CU", "Cuba", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Grand_Turk".toLowerCase(), new TimezoneInfo("America/Grand_Turk", "NA", "North America", "TC", "Turks and Caicos Islands", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Nassau".toLowerCase(), new TimezoneInfo("America/Nassau", "NA", "North America", "BS", "Bahamas", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Detroit".toLowerCase(), new TimezoneInfo("America/Detroit", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Indiana/Indianapolis".toLowerCase(), new TimezoneInfo("America/Indiana/Indianapolis", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Indiana/Marengo".toLowerCase(), new TimezoneInfo("America/Indiana/Marengo", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Indiana/Petersburg".toLowerCase(), new TimezoneInfo("America/Indiana/Petersburg", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Indiana/Vevay".toLowerCase(), new TimezoneInfo("America/Indiana/Vevay", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Indiana/Vincennes".toLowerCase(), new TimezoneInfo("America/Indiana/Vincennes", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Indiana/Winamac".toLowerCase(), new TimezoneInfo("America/Indiana/Winamac", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Kentucky/Louisville".toLowerCase(), new TimezoneInfo("America/Kentucky/Louisville", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Kentucky/Monticello".toLowerCase(), new TimezoneInfo("America/Kentucky/Monticello", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/New_York".toLowerCase(), new TimezoneInfo("America/New_York", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("US/Michigan".toLowerCase(), new TimezoneInfo("US/Michigan", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Fort_Wayne".toLowerCase(), new TimezoneInfo("America/Fort_Wayne", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Indianapolis".toLowerCase(), new TimezoneInfo("America/Indianapolis", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("US/East-Indiana".toLowerCase(), new TimezoneInfo("US/East-Indiana", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Louisville".toLowerCase(), new TimezoneInfo("America/Louisville", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("US/Eastern".toLowerCase(), new TimezoneInfo("US/Eastern", "NA", "North America", "US", "United States", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Port-au-Prince".toLowerCase(), new TimezoneInfo("America/Port-au-Prince", "NA", "North America", "HT", "Haiti", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Iqaluit".toLowerCase(), new TimezoneInfo("America/Iqaluit", "NA", "North America", "CA", "Canada", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Nipigon".toLowerCase(), new TimezoneInfo("America/Nipigon", "NA", "North America", "CA", "Canada", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Pangnirtung".toLowerCase(), new TimezoneInfo("America/Pangnirtung", "NA", "North America", "CA", "Canada", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Thunder_Bay".toLowerCase(), new TimezoneInfo("America/Thunder_Bay", "NA", "North America", "CA", "Canada", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Toronto".toLowerCase(), new TimezoneInfo("America/Toronto", "NA", "North America", "CA", "Canada", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Montreal".toLowerCase(), new TimezoneInfo("America/Montreal", "NA", "North America", "CA", "Canada", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("Canada/Eastern".toLowerCase(), new TimezoneInfo("Canada/Eastern", "NA", "North America", "CA", "Canada", AppLovinErrorCodes.INCENTIVIZED_NO_AD_PRELOADED));
        this.countries.put("America/Guyana".toLowerCase(), new TimezoneInfo("America/Guyana", "SA", "South America", "GY", "Guyana", -240));
        this.countries.put("America/Asuncion".toLowerCase(), new TimezoneInfo("America/Asuncion", "SA", "South America", "PY", "Paraguay", -240));
        this.countries.put("America/Caracas".toLowerCase(), new TimezoneInfo("America/Caracas", "SA", "South America", "VE", "Venezuela", -240));
        this.countries.put("America/Argentina/Buenos_Aires".toLowerCase(), new TimezoneInfo("America/Argentina/Buenos_Aires", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/Catamarca".toLowerCase(), new TimezoneInfo("America/Argentina/Catamarca", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/Cordoba".toLowerCase(), new TimezoneInfo("America/Argentina/Cordoba", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/Jujuy".toLowerCase(), new TimezoneInfo("America/Argentina/Jujuy", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/La_Rioja".toLowerCase(), new TimezoneInfo("America/Argentina/La_Rioja", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/Mendoza".toLowerCase(), new TimezoneInfo("America/Argentina/Mendoza", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/Rio_Gallegos".toLowerCase(), new TimezoneInfo("America/Argentina/Rio_Gallegos", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/Salta".toLowerCase(), new TimezoneInfo("America/Argentina/Salta", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/San_Juan".toLowerCase(), new TimezoneInfo("America/Argentina/San_Juan", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/San_Luis".toLowerCase(), new TimezoneInfo("America/Argentina/San_Luis", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/Tucuman".toLowerCase(), new TimezoneInfo("America/Argentina/Tucuman", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/Ushuaia".toLowerCase(), new TimezoneInfo("America/Argentina/Ushuaia", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Buenos_Aires".toLowerCase(), new TimezoneInfo("America/Buenos_Aires", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Argentina/ComodRivadavia".toLowerCase(), new TimezoneInfo("America/Argentina/ComodRivadavia", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Catamarca".toLowerCase(), new TimezoneInfo("America/Catamarca", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Cordoba".toLowerCase(), new TimezoneInfo("America/Cordoba", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Rosario".toLowerCase(), new TimezoneInfo("America/Rosario", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Jujuy".toLowerCase(), new TimezoneInfo("America/Jujuy", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Mendoza".toLowerCase(), new TimezoneInfo("America/Mendoza", "SA", "South America", "AR", "Argentina", -180));
        this.countries.put("America/Glace_Bay".toLowerCase(), new TimezoneInfo("America/Glace_Bay", "NA", "North America", "CA", "Canada", -240));
        this.countries.put("America/Goose_Bay".toLowerCase(), new TimezoneInfo("America/Goose_Bay", "NA", "North America", "CA", "Canada", -240));
        this.countries.put("America/Halifax".toLowerCase(), new TimezoneInfo("America/Halifax", "NA", "North America", "CA", "Canada", -240));
        this.countries.put("America/Moncton".toLowerCase(), new TimezoneInfo("America/Moncton", "NA", "North America", "CA", "Canada", -240));
        this.countries.put("Canada/Atlantic".toLowerCase(), new TimezoneInfo("Canada/Atlantic", "NA", "North America", "CA", "Canada", -240));
        this.countries.put("Atlantic/Bermuda".toLowerCase(), new TimezoneInfo("Atlantic/Bermuda", "NA", "North America", "BM", "Bermuda", -240));
        this.countries.put("America/Thule".toLowerCase(), new TimezoneInfo("America/Thule", "NA", "North America", "GL", "Greenland", -240));
        this.countries.put("America/Araguaina".toLowerCase(), new TimezoneInfo("America/Araguaina", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("America/Bahia".toLowerCase(), new TimezoneInfo("America/Bahia", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("America/Belem".toLowerCase(), new TimezoneInfo("America/Belem", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("America/Fortaleza".toLowerCase(), new TimezoneInfo("America/Fortaleza", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("America/Maceio".toLowerCase(), new TimezoneInfo("America/Maceio", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("America/Recife".toLowerCase(), new TimezoneInfo("America/Recife", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("America/Santarem".toLowerCase(), new TimezoneInfo("America/Santarem", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("America/Sao_Paulo".toLowerCase(), new TimezoneInfo("America/Sao_Paulo", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("Brazil/East".toLowerCase(), new TimezoneInfo("Brazil/East", "SA", "South America", "BR", "Brazil", -180));
        this.countries.put("Antarctica/Palmer".toLowerCase(), new TimezoneInfo("Antarctica/Palmer", "AN", "Antarctica", "AQ", "Antarctica", -180));
        this.countries.put("Antarctica/Rothera".toLowerCase(), new TimezoneInfo("Antarctica/Rothera", "AN", "Antarctica", "AQ", "Antarctica", -180));
        this.countries.put("America/Punta_Arenas".toLowerCase(), new TimezoneInfo("America/Punta_Arenas", "SA", "South America", "CL", "Chile", -180));
        this.countries.put("America/Santiago".toLowerCase(), new TimezoneInfo("America/Santiago", "SA", "South America", "CL", "Chile", -240));
        this.countries.put("Chile/Continental".toLowerCase(), new TimezoneInfo("Chile/Continental", "SA", "South America", "CL", "Chile", -240));
        this.countries.put("Atlantic/Stanley".toLowerCase(), new TimezoneInfo("Atlantic/Stanley", "SA", "South America", "FK", "Falkland Islands", -180));
        this.countries.put("America/Cayenne".toLowerCase(), new TimezoneInfo("America/Cayenne", "SA", "South America", "GF", "French Guiana", -180));
        this.countries.put("America/Paramaribo".toLowerCase(), new TimezoneInfo("America/Paramaribo", "SA", "South America", "SR", "Suriname", -180));
        this.countries.put("America/Montevideo".toLowerCase(), new TimezoneInfo("America/Montevideo", "SA", "South America", "UY", "Uruguay", -180));
        this.countries.put("America/St_Johns".toLowerCase(), new TimezoneInfo("America/St_Johns", "NA", "North America", "CA", "Canada", -210));
        this.countries.put("Canada/Newfoundland".toLowerCase(), new TimezoneInfo("Canada/Newfoundland", "NA", "North America", "CA", "Canada", -210));
        this.countries.put("America/Noronha".toLowerCase(), new TimezoneInfo("America/Noronha", "SA", "South America", "BR", "Brazil", -120));
        this.countries.put("Brazil/DeNoronha".toLowerCase(), new TimezoneInfo("Brazil/DeNoronha", "SA", "South America", "BR", "Brazil", -120));
        this.countries.put("Atlantic/South_Georgia".toLowerCase(), new TimezoneInfo("Atlantic/South_Georgia", "AN", "Antarctica", "GS", "South Georgia and the South Sandwich Islands", -120));
        this.countries.put("America/Miquelon".toLowerCase(), new TimezoneInfo("America/Miquelon", "NA", "North America", "PM", "Saint Pierre and Miquelon", -180));
        this.countries.put("America/Nuuk".toLowerCase(), new TimezoneInfo("America/Nuuk", "NA", "North America", "GL", "Greenland", -180));
        this.countries.put("America/Godthab".toLowerCase(), new TimezoneInfo("America/Godthab", "NA", "North America", "GL", "Greenland", -180));
        this.countries.put("Atlantic/Cape_Verde".toLowerCase(), new TimezoneInfo("Atlantic/Cape_Verde", "AF", "Africa", "CV", "Cabo Verde", -60));
        this.countries.put("Atlantic/Azores".toLowerCase(), new TimezoneInfo("Atlantic/Azores", "EU", "Europe", "PT", "Portugal", -60));
        this.countries.put("America/Scoresbysund".toLowerCase(), new TimezoneInfo("America/Scoresbysund", "NA", "North America", "GL", "Greenland", -60));
        this.countries.put("Africa/Abidjan".toLowerCase(), new TimezoneInfo("Africa/Abidjan", "AF", "Africa", "CI", "Ivory Coast", 0));
        this.countries.put("Africa/Timbuktu".toLowerCase(), new TimezoneInfo("Africa/Timbuktu", "AF", "Africa", "CI", "Ivory Coast", 0));
        this.countries.put("Iceland".toLowerCase(), new TimezoneInfo("Iceland", "EU", "Europe", IronSourceConstants.INTERSTITIAL_EVENT_TYPE, "Iceland", 0));
        this.countries.put("Africa/Accra".toLowerCase(), new TimezoneInfo("Africa/Accra", "AF", "Africa", "GH", "Ghana", 0));
        this.countries.put("Africa/Bamako".toLowerCase(), new TimezoneInfo("Africa/Bamako", "AF", "Africa", "ML", "Mali", 0));
        this.countries.put("Africa/Bissau".toLowerCase(), new TimezoneInfo("Africa/Bissau", "AF", "Africa", "GW", "Guinea-Bissau", 0));
        this.countries.put("Africa/Conakry".toLowerCase(), new TimezoneInfo("Africa/Conakry", "AF", "Africa", "GN", "Guinea", 0));
        this.countries.put("Africa/Dakar".toLowerCase(), new TimezoneInfo("Africa/Dakar", "AF", "Africa", "SN", "Senegal", 0));
        this.countries.put("America/Danmarkshavn".toLowerCase(), new TimezoneInfo("America/Danmarkshavn", "NA", "North America", "GL", "Greenland", 0));
        this.countries.put("Africa/Freetown".toLowerCase(), new TimezoneInfo("Africa/Freetown", "AF", "Africa", "SL", "Sierra Leone", 0));
        this.countries.put("Atlantic/St_Helena".toLowerCase(), new TimezoneInfo("Atlantic/St_Helena", "AF", "Africa", "SH", "Saint Helena", 0));
        this.countries.put("Africa/Lome".toLowerCase(), new TimezoneInfo("Africa/Lome", "AF", "Africa", "TG", "Togo", 0));
        this.countries.put("Africa/Monrovia".toLowerCase(), new TimezoneInfo("Africa/Monrovia", "AF", "Africa", "LR", "Liberia", 0));
        this.countries.put("Africa/Nouakchott".toLowerCase(), new TimezoneInfo("Africa/Nouakchott", "AF", "Africa", "MR", "Mauritania", 0));
        this.countries.put("Africa/Ouagadougou".toLowerCase(), new TimezoneInfo("Africa/Ouagadougou", "AF", "Africa", "BF", "Burkina Faso", 0));
        this.countries.put("Atlantic/Reykjavik".toLowerCase(), new TimezoneInfo("Atlantic/Reykjavik", "EU", "Europe", IronSourceConstants.INTERSTITIAL_EVENT_TYPE, "Iceland", 0));
        this.countries.put("Africa/Sao_Tome".toLowerCase(), new TimezoneInfo("Africa/Sao_Tome", "AF", "Africa", "ST", "Sao Tome and Principe", 0));
        this.countries.put("Africa/Banjul".toLowerCase(), new TimezoneInfo("Africa/Banjul", "AF", "Africa", "GM", "Gambia", 0));
        this.countries.put("Africa/Algiers".toLowerCase(), new TimezoneInfo("Africa/Algiers", "AF", "Africa", "DZ", "Algeria", 60));
        this.countries.put("Africa/Tunis".toLowerCase(), new TimezoneInfo("Africa/Tunis", "AF", "Africa", "TN", "Tunisia", 60));
        this.countries.put("Europe/Isle_of_Man".toLowerCase(), new TimezoneInfo("Europe/Isle_of_Man", "EU", "Europe", "IM", "Isle of Man", 0));
        this.countries.put("Europe/Dublin".toLowerCase(), new TimezoneInfo("Europe/Dublin", "EU", "Europe", "IE", "Ireland", 0));
        this.countries.put("Eire".toLowerCase(), new TimezoneInfo("Eire", "EU", "Europe", "IE", "Ireland", 0));
        this.countries.put("Europe/London".toLowerCase(), new TimezoneInfo("Europe/London", "EU", "Europe", "GB", "United Kingdom", 0));
        this.countries.put("Europe/Belfast".toLowerCase(), new TimezoneInfo("Europe/Belfast", "EU", "Europe", "GB", "United Kingdom", 0));
        this.countries.put("GB".toLowerCase(), new TimezoneInfo("GB", "EU", "Europe", "GB", "United Kingdom", 0));
        this.countries.put("GB-Eire".toLowerCase(), new TimezoneInfo("GB-Eire", "EU", "Europe", "GB", "United Kingdom", 0));
        this.countries.put("Europe/Jersey".toLowerCase(), new TimezoneInfo("Europe/Jersey", "EU", "Europe", "JE", "Jersey", 0));
        this.countries.put("Europe/Guernsey".toLowerCase(), new TimezoneInfo("Europe/Guernsey", "EU", "Europe", "GG", "Guernsey", 0));
        this.countries.put("Africa/Bangui".toLowerCase(), new TimezoneInfo("Africa/Bangui", "AF", "Africa", "CF", "Central African Republic", 60));
        this.countries.put("Africa/Malabo".toLowerCase(), new TimezoneInfo("Africa/Malabo", "AF", "Africa", "GQ", "Equatorial Guinea", 60));
        this.countries.put("Africa/Brazzaville".toLowerCase(), new TimezoneInfo("Africa/Brazzaville", "AF", "Africa", "CG", "Republic of the Congo", 60));
        this.countries.put("Africa/Porto-Novo".toLowerCase(), new TimezoneInfo("Africa/Porto-Novo", "AF", "Africa", "BJ", "Benin", 60));
        this.countries.put("Africa/Douala".toLowerCase(), new TimezoneInfo("Africa/Douala", "AF", "Africa", "CM", "Cameroon", 60));
        this.countries.put("Africa/Kinshasa".toLowerCase(), new TimezoneInfo("Africa/Kinshasa", "AF", "Africa", "CD", "Democratic Republic of the Congo", 60));
        this.countries.put("Africa/Lagos".toLowerCase(), new TimezoneInfo("Africa/Lagos", "AF", "Africa", "NG", "Nigeria", 60));
        this.countries.put("Africa/Libreville".toLowerCase(), new TimezoneInfo("Africa/Libreville", "AF", "Africa", "GA", "Gabon", 60));
        this.countries.put("Africa/Luanda".toLowerCase(), new TimezoneInfo("Africa/Luanda", "AF", "Africa", "AO", "Angola", 60));
        this.countries.put("Africa/Ndjamena".toLowerCase(), new TimezoneInfo("Africa/Ndjamena", "AF", "Africa", "TD", "Chad", 60));
        this.countries.put("Africa/Niamey".toLowerCase(), new TimezoneInfo("Africa/Niamey", "AF", "Africa", "NE", "Niger", 60));
        this.countries.put("Africa/Casablanca".toLowerCase(), new TimezoneInfo("Africa/Casablanca", "AF", "Africa", RequestConfiguration.MAX_AD_CONTENT_RATING_MA, "Morocco", 0));
        this.countries.put("Africa/El_Aaiun".toLowerCase(), new TimezoneInfo("Africa/El_Aaiun", "AF", "Africa", "EH", "Western Sahara", 0));
        this.countries.put("Atlantic/Canary".toLowerCase(), new TimezoneInfo("Atlantic/Canary", "EU", "Europe", "ES", "Spain", 0));
        this.countries.put("Atlantic/Madeira".toLowerCase(), new TimezoneInfo("Atlantic/Madeira", "EU", "Europe", "PT", "Portugal", 0));
        this.countries.put("Europe/Lisbon".toLowerCase(), new TimezoneInfo("Europe/Lisbon", "EU", "Europe", "PT", "Portugal", 0));
        this.countries.put("Portugal".toLowerCase(), new TimezoneInfo("Portugal", "EU", "Europe", "PT", "Portugal", 0));
        this.countries.put("Atlantic/Faroe".toLowerCase(), new TimezoneInfo("Atlantic/Faroe", "EU", "Europe", "FO", "Faroe Islands", 0));
        this.countries.put("Atlantic/Faeroe".toLowerCase(), new TimezoneInfo("Atlantic/Faeroe", "EU", "Europe", "FO", "Faroe Islands", 0));
        this.countries.put("Africa/Bujumbura".toLowerCase(), new TimezoneInfo("Africa/Bujumbura", "AF", "Africa", "BI", "Burundi", 120));
        this.countries.put("Africa/Gaborone".toLowerCase(), new TimezoneInfo("Africa/Gaborone", "AF", "Africa", "BW", "Botswana", 120));
        this.countries.put("Africa/Harare".toLowerCase(), new TimezoneInfo("Africa/Harare", "AF", "Africa", "ZW", "Zimbabwe", 120));
        this.countries.put("Africa/Juba".toLowerCase(), new TimezoneInfo("Africa/Juba", "AF", "Africa", "SS", "South Sudan", 120));
        this.countries.put("Africa/Khartoum".toLowerCase(), new TimezoneInfo("Africa/Khartoum", "AF", "Africa", "SD", "Sudan", 120));
        this.countries.put("Africa/Kigali".toLowerCase(), new TimezoneInfo("Africa/Kigali", "AF", "Africa", "RW", "Rwanda", 120));
        this.countries.put("Africa/Blantyre".toLowerCase(), new TimezoneInfo("Africa/Blantyre", "AF", "Africa", "MW", "Malawi", 120));
        this.countries.put("Africa/Lubumbashi".toLowerCase(), new TimezoneInfo("Africa/Lubumbashi", "AF", "Africa", "CD", "Democratic Republic of the Congo", 120));
        this.countries.put("Africa/Lusaka".toLowerCase(), new TimezoneInfo("Africa/Lusaka", "AF", "Africa", "ZM", "Zambia", 120));
        this.countries.put("Africa/Maputo".toLowerCase(), new TimezoneInfo("Africa/Maputo", "AF", "Africa", "MZ", "Mozambique", 120));
        this.countries.put("Africa/Windhoek".toLowerCase(), new TimezoneInfo("Africa/Windhoek", "AF", "Africa", "NA", "Namibia", 60));
        this.countries.put("Europe/Amsterdam".toLowerCase(), new TimezoneInfo("Europe/Amsterdam", "EU", "Europe", "NL", "Netherlands", 60));
        this.countries.put("Europe/Andorra".toLowerCase(), new TimezoneInfo("Europe/Andorra", "EU", "Europe", "AD", "Andorra", 60));
        this.countries.put("Europe/Belgrade".toLowerCase(), new TimezoneInfo("Europe/Belgrade", "EU", "Europe", "RS", "Serbia", 60));
        this.countries.put("Europe/Berlin".toLowerCase(), new TimezoneInfo("Europe/Berlin", "EU", "Europe", "DE", "Germany", 60));
        this.countries.put("Europe/Busingen".toLowerCase(), new TimezoneInfo("Europe/Busingen", "EU", "Europe", "CH", "Switzerland", 60));
        this.countries.put("Atlantic/Jan_Mayen".toLowerCase(), new TimezoneInfo("Atlantic/Jan_Mayen", "EU", "Europe", "NO", "Norway", 60));
        this.countries.put("Europe/Malta".toLowerCase(), new TimezoneInfo("Europe/Malta", "EU", "Europe", "MT", "Malta", 60));
        this.countries.put("Europe/Bratislava".toLowerCase(), new TimezoneInfo("Europe/Bratislava", "EU", "Europe", "SK", "Slovakia", 60));
        this.countries.put("Europe/Brussels".toLowerCase(), new TimezoneInfo("Europe/Brussels", "EU", "Europe", "BE", "Belgium", 60));
        this.countries.put("Europe/Budapest".toLowerCase(), new TimezoneInfo("Europe/Budapest", "EU", "Europe", "HU", "Hungary", 60));
        this.countries.put("Europe/Copenhagen".toLowerCase(), new TimezoneInfo("Europe/Copenhagen", "EU", "Europe", "DK", "Denmark", 60));
        this.countries.put("Europe/Gibraltar".toLowerCase(), new TimezoneInfo("Europe/Gibraltar", "EU", "Europe", "GI", "Gibraltar", 60));
        this.countries.put("Europe/Ljubljana".toLowerCase(), new TimezoneInfo("Europe/Ljubljana", "EU", "Europe", "SI", "Slovenia", 60));
        this.countries.put("Arctic/Longyearbyen".toLowerCase(), new TimezoneInfo("Arctic/Longyearbyen", "EU", "Europe", "SJ", "Svalbard and Jan Mayen", 60));
        this.countries.put("Europe/Luxembourg".toLowerCase(), new TimezoneInfo("Europe/Luxembourg", "EU", "Europe", "LU", "Luxembourg", 60));
        this.countries.put("Africa/Ceuta".toLowerCase(), new TimezoneInfo("Africa/Ceuta", "EU", "Europe", "ES", "Spain", 60));
        this.countries.put("Europe/Madrid".toLowerCase(), new TimezoneInfo("Europe/Madrid", "EU", "Europe", "ES", "Spain", 60));
        this.countries.put("Europe/Monaco".toLowerCase(), new TimezoneInfo("Europe/Monaco", "EU", "Europe", "MC", "Monaco", 60));
        this.countries.put("Europe/Oslo".toLowerCase(), new TimezoneInfo("Europe/Oslo", "EU", "Europe", "NO", "Norway", 60));
        this.countries.put("Europe/Paris".toLowerCase(), new TimezoneInfo("Europe/Paris", "EU", "Europe", "FR", "France", 60));
        this.countries.put("Europe/Podgorica".toLowerCase(), new TimezoneInfo("Europe/Podgorica", "EU", "Europe", "ME", "Montenegro", 60));
        this.countries.put("Europe/Prague".toLowerCase(), new TimezoneInfo("Europe/Prague", "EU", "Europe", "CZ", "Czechia", 60));
        this.countries.put("Europe/Rome".toLowerCase(), new TimezoneInfo("Europe/Rome", "EU", "Europe", "IT", "Italy", 60));
        this.countries.put("Europe/San_Marino".toLowerCase(), new TimezoneInfo("Europe/San_Marino", "EU", "Europe", "SM", "San Marino", 60));
        this.countries.put("Europe/Sarajevo".toLowerCase(), new TimezoneInfo("Europe/Sarajevo", "EU", "Europe", "BA", "Bosnia and Herzegovina", 60));
        this.countries.put("Europe/Skopje".toLowerCase(), new TimezoneInfo("Europe/Skopje", "EU", "Europe", "MK", "North Macedonia", 60));
        this.countries.put("Europe/Stockholm".toLowerCase(), new TimezoneInfo("Europe/Stockholm", "EU", "Europe", "SE", "Sweden", 60));
        this.countries.put("Europe/Tirane".toLowerCase(), new TimezoneInfo("Europe/Tirane", "EU", "Europe", "AL", "Albania", 60));
        this.countries.put("Europe/Vaduz".toLowerCase(), new TimezoneInfo("Europe/Vaduz", "EU", "Europe", "LI", "Liechtenstein", 60));
        this.countries.put("Europe/Vatican".toLowerCase(), new TimezoneInfo("Europe/Vatican", "EU", "Europe", "VA", "Vatican", 60));
        this.countries.put("Europe/Vienna".toLowerCase(), new TimezoneInfo("Europe/Vienna", "EU", "Europe", "AT", "Austria", 60));
        this.countries.put("Europe/Warsaw".toLowerCase(), new TimezoneInfo("Europe/Warsaw", "EU", "Europe", "PL", "Poland", 60));
        this.countries.put("Poland".toLowerCase(), new TimezoneInfo("Poland", "EU", "Europe", "PL", "Poland", 60));
        this.countries.put("Europe/Zagreb".toLowerCase(), new TimezoneInfo("Europe/Zagreb", "EU", "Europe", "HR", "Croatia", 60));
        this.countries.put("Europe/Zurich".toLowerCase(), new TimezoneInfo("Europe/Zurich", "EU", "Europe", "CH", "Switzerland", 60));
        this.countries.put("Africa/Cairo".toLowerCase(), new TimezoneInfo("Africa/Cairo", "AF", "Africa", "EG", "Egypt", 120));
        this.countries.put("Egypt".toLowerCase(), new TimezoneInfo("Egypt", "AF", "Africa", "EG", "Egypt", 120));
        this.countries.put("Europe/Kaliningrad".toLowerCase(), new TimezoneInfo("Europe/Kaliningrad", "EU", "Europe", "RU", "Russia", 120));
        this.countries.put("Africa/Tripoli".toLowerCase(), new TimezoneInfo("Africa/Tripoli", "AF", "Africa", "LY", "Libya", 120));
        this.countries.put("Libya".toLowerCase(), new TimezoneInfo("Libya", "AF", "Africa", "LY", "Libya", 120));
        this.countries.put("Antarctica/Troll".toLowerCase(), new TimezoneInfo("Antarctica/Troll", "AN", "Antarctica", "AQ", "Antarctica", 0));
        this.countries.put("Africa/Johannesburg".toLowerCase(), new TimezoneInfo("Africa/Johannesburg", "AF", "Africa", "ZA", "South Africa", 120));
        this.countries.put("Africa/Mbabane".toLowerCase(), new TimezoneInfo("Africa/Mbabane", "AF", "Africa", "SZ", "Eswatini", 120));
        this.countries.put("Africa/Maseru".toLowerCase(), new TimezoneInfo("Africa/Maseru", "AF", "Africa", "LS", "Lesotho", 120));
        this.countries.put("Asia/Kuwait".toLowerCase(), new TimezoneInfo("Asia/Kuwait", "AS", "Asia", "KW", "Kuwait", 180));
        this.countries.put("Asia/Baghdad".toLowerCase(), new TimezoneInfo("Asia/Baghdad", "AS", "Asia", "IQ", "Iraq", 180));
        this.countries.put("Asia/Qatar".toLowerCase(), new TimezoneInfo("Asia/Qatar", "AS", "Asia", "QA", "Qatar", 180));
        this.countries.put("Asia/Bahrain".toLowerCase(), new TimezoneInfo("Asia/Bahrain", "AS", "Asia", "BH", "Bahrain", 180));
        this.countries.put("Asia/Riyadh".toLowerCase(), new TimezoneInfo("Asia/Riyadh", "AS", "Asia", "SA", "Saudi Arabia", 180));
        this.countries.put("Asia/Aden".toLowerCase(), new TimezoneInfo("Asia/Aden", "AS", "Asia", "YE", "Yemen", 180));
        this.countries.put("Africa/Addis_Ababa".toLowerCase(), new TimezoneInfo("Africa/Addis_Ababa", "AF", "Africa", "ET", "Ethiopia", 180));
        this.countries.put("Indian/Antananarivo".toLowerCase(), new TimezoneInfo("Indian/Antananarivo", "AF", "Africa", "MG", "Madagascar", 180));
        this.countries.put("Africa/Asmara".toLowerCase(), new TimezoneInfo("Africa/Asmara", "AF", "Africa", "ER", "Eritrea", 180));
        this.countries.put("Africa/Dar_es_Salaam".toLowerCase(), new TimezoneInfo("Africa/Dar_es_Salaam", "AF", "Africa", "TZ", "Tanzania", 180));
        this.countries.put("Africa/Djibouti".toLowerCase(), new TimezoneInfo("Africa/Djibouti", "AF", "Africa", "DJ", "Djibouti", 180));
        this.countries.put("Africa/Kampala".toLowerCase(), new TimezoneInfo("Africa/Kampala", "AF", "Africa", "UG", "Uganda", 180));
        this.countries.put("Indian/Mayotte".toLowerCase(), new TimezoneInfo("Indian/Mayotte", "AF", "Africa", "YT", "Mayotte", 180));
        this.countries.put("Africa/Mogadishu".toLowerCase(), new TimezoneInfo("Africa/Mogadishu", "AF", "Africa", "SO", "Somalia", 180));
        this.countries.put("Indian/Comoro".toLowerCase(), new TimezoneInfo("Indian/Comoro", "AF", "Africa", "KM", "Comoros", 180));
        this.countries.put("Africa/Nairobi".toLowerCase(), new TimezoneInfo("Africa/Nairobi", "AF", "Africa", "KE", "Kenya", 180));
        this.countries.put("Africa/Asmera".toLowerCase(), new TimezoneInfo("Africa/Asmera", "AF", "Africa", "KE", "Kenya", 180));
        this.countries.put("Asia/Damascus".toLowerCase(), new TimezoneInfo("Asia/Damascus", "AS", "Asia", "SY", "Syria", 120));
        this.countries.put("Asia/Amman".toLowerCase(), new TimezoneInfo("Asia/Amman", "AS", "Asia", "JO", "Jordan", 120));
        this.countries.put("Europe/Athens".toLowerCase(), new TimezoneInfo("Europe/Athens", "EU", "Europe", "GR", "Greece", 120));
        this.countries.put("Asia/Beirut".toLowerCase(), new TimezoneInfo("Asia/Beirut", "AS", "Asia", "LB", "Lebanon", 120));
        this.countries.put("Europe/Bucharest".toLowerCase(), new TimezoneInfo("Europe/Bucharest", "EU", "Europe", "RO", "Romania", 120));
        this.countries.put("Europe/Chisinau".toLowerCase(), new TimezoneInfo("Europe/Chisinau", "EU", "Europe", "MD", "Moldova", 120));
        this.countries.put("Europe/Tiraspol".toLowerCase(), new TimezoneInfo("Europe/Tiraspol", "EU", "Europe", "MD", "Moldova", 120));
        this.countries.put("Asia/Gaza".toLowerCase(), new TimezoneInfo("Asia/Gaza", "AS", "Asia", "PS", "Palestinian Territory", 120));
        this.countries.put("Asia/Hebron".toLowerCase(), new TimezoneInfo("Asia/Hebron", "AS", "Asia", "PS", "Palestinian Territory", 120));
        this.countries.put("Europe/Helsinki".toLowerCase(), new TimezoneInfo("Europe/Helsinki", "EU", "Europe", "FI", "Finland", 120));
        this.countries.put("Europe/Mariehamn".toLowerCase(), new TimezoneInfo("Europe/Mariehamn", "EU", "Europe", "AX", "Aland Islands", 120));
        this.countries.put("Asia/Famagusta".toLowerCase(), new TimezoneInfo("Asia/Famagusta", "EU", "Europe", "CY", "Cyprus", 120));
        this.countries.put("Asia/Nicosia".toLowerCase(), new TimezoneInfo("Asia/Nicosia", "EU", "Europe", "CY", "Cyprus", 120));
        this.countries.put("Europe/Nicosia".toLowerCase(), new TimezoneInfo("Europe/Nicosia", "EU", "Europe", "CY", "Cyprus", 120));
        this.countries.put("Europe/Riga".toLowerCase(), new TimezoneInfo("Europe/Riga", "EU", "Europe", "LV", "Latvia", 120));
        this.countries.put("Europe/Sofia".toLowerCase(), new TimezoneInfo("Europe/Sofia", "EU", "Europe", "BG", "Bulgaria", 120));
        this.countries.put("Europe/Tallinn".toLowerCase(), new TimezoneInfo("Europe/Tallinn", "EU", "Europe", "EE", "Estonia", 120));
        this.countries.put("Europe/Vilnius".toLowerCase(), new TimezoneInfo("Europe/Vilnius", "EU", "Europe", "LT", "Lithuania", 120));
        this.countries.put("Europe/Uzhgorod".toLowerCase(), new TimezoneInfo("Europe/Uzhgorod", "EU", "Europe", "UA", "Ukraine", 120));
        this.countries.put("Europe/Zaporozhye".toLowerCase(), new TimezoneInfo("Europe/Zaporozhye", "EU", "Europe", "UA", "Ukraine", 120));
        this.countries.put("Asia/Jerusalem".toLowerCase(), new TimezoneInfo("Asia/Jerusalem", "AS", "Asia", "IL", "Israel", 120));
        this.countries.put("Asia/Tel_Aviv".toLowerCase(), new TimezoneInfo("Asia/Tel_Aviv", "AS", "Asia", "IL", "Israel", 120));
        this.countries.put("Israel".toLowerCase(), new TimezoneInfo("Israel", "AS", "Asia", "IL", "Israel", 120));
        this.countries.put("Europe/Minsk".toLowerCase(), new TimezoneInfo("Europe/Minsk", "EU", "Europe", "BY", "Belarus", 180));
        this.countries.put("Europe/Kirov".toLowerCase(), new TimezoneInfo("Europe/Kirov", "EU", "Europe", "RU", "Russia", 180));
        this.countries.put("Europe/Moscow".toLowerCase(), new TimezoneInfo("Europe/Moscow", "EU", "Europe", "RU", "Russia", 180));
        this.countries.put("Europe/Volgograd".toLowerCase(), new TimezoneInfo("Europe/Volgograd", "EU", "Europe", "RU", "Russia", 180));
        this.countries.put("W-SU".toLowerCase(), new TimezoneInfo("W-SU", "EU", "Europe", "RU", "Russia", 180));
        this.countries.put("Europe/Simferopol".toLowerCase(), new TimezoneInfo("Europe/Simferopol", "EU", "Europe", "UA", "Ukraine", 180));
        this.countries.put("Antarctica/Syowa".toLowerCase(), new TimezoneInfo("Antarctica/Syowa", "AN", "Antarctica", "AQ", "Antarctica", 180));
        this.countries.put("Europe/Istanbul".toLowerCase(), new TimezoneInfo("Europe/Istanbul", "AS", "Asia", "TR", "Turkey", 180));
        this.countries.put("Turkey".toLowerCase(), new TimezoneInfo("Turkey", "AS", "Asia", "TR", "Turkey", 180));
        this.countries.put("Asia/Istanbul".toLowerCase(), new TimezoneInfo("Asia/Istanbul", "AS", "Asia", "TR", "Turkey", 180));
        this.countries.put("Asia/Yerevan".toLowerCase(), new TimezoneInfo("Asia/Yerevan", "AS", "Asia", "AM", "Armenia", 240));
        this.countries.put("Asia/Baku".toLowerCase(), new TimezoneInfo("Asia/Baku", "AS", "Asia", "AZ", "Azerbaijan", 240));
        this.countries.put("Asia/Tbilisi".toLowerCase(), new TimezoneInfo("Asia/Tbilisi", "AS", "Asia", "GE", "Georgia", 240));
        this.countries.put("Asia/Dubai".toLowerCase(), new TimezoneInfo("Asia/Dubai", "AS", "Asia", "AE", "United Arab Emirates", 240));
        this.countries.put("Asia/Muscat".toLowerCase(), new TimezoneInfo("Asia/Muscat", "AS", "Asia", "OM", "Oman", 240));
        this.countries.put("Indian/Mauritius".toLowerCase(), new TimezoneInfo("Indian/Mauritius", "AF", "Africa", "MU", "Mauritius", 240));
        this.countries.put("Indian/Reunion".toLowerCase(), new TimezoneInfo("Indian/Reunion", "AF", "Africa", "RE", "Reunion", 240));
        this.countries.put("Europe/Astrakhan".toLowerCase(), new TimezoneInfo("Europe/Astrakhan", "EU", "Europe", "RU", "Russia", 240));
        this.countries.put("Europe/Samara".toLowerCase(), new TimezoneInfo("Europe/Samara", "EU", "Europe", "RU", "Russia", 240));
        this.countries.put("Europe/Saratov".toLowerCase(), new TimezoneInfo("Europe/Saratov", "EU", "Europe", "RU", "Russia", 240));
        this.countries.put("Europe/Ulyanovsk".toLowerCase(), new TimezoneInfo("Europe/Ulyanovsk", "EU", "Europe", "RU", "Russia", 240));
        this.countries.put("Indian/Mahe".toLowerCase(), new TimezoneInfo("Indian/Mahe", "AF", "Africa", "SC", "Seychelles", 240));
        this.countries.put("Asia/Kabul".toLowerCase(), new TimezoneInfo("Asia/Kabul", "AS", "Asia", "AF", "Afghanistan", 270));
        this.countries.put("Asia/Tehran".toLowerCase(), new TimezoneInfo("Asia/Tehran", "AS", "Asia", "IR", "Iran", 210));
        this.countries.put("Iran".toLowerCase(), new TimezoneInfo("Iran", "AS", "Asia", "IR", "Iran", 210));
        this.countries.put("Indian/Kerguelen".toLowerCase(), new TimezoneInfo("Indian/Kerguelen", "AN", "Antarctica", "TF", "French Southern Territories", c.COLLECT_MODE_FINANCE));
        this.countries.put("Indian/Maldives".toLowerCase(), new TimezoneInfo("Indian/Maldives", "AS", "Asia", "MV", "Maldives", c.COLLECT_MODE_FINANCE));
        this.countries.put("Antarctica/Mawson".toLowerCase(), new TimezoneInfo("Antarctica/Mawson", "AN", "Antarctica", "AQ", "Antarctica", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Karachi".toLowerCase(), new TimezoneInfo("Asia/Karachi", "AS", "Asia", "PK", "Pakistan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Dushanbe".toLowerCase(), new TimezoneInfo("Asia/Dushanbe", "AS", "Asia", "TJ", "Tajikistan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Ashgabat".toLowerCase(), new TimezoneInfo("Asia/Ashgabat", "AS", "Asia", "TM", "Turkmenistan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Ashkhabad".toLowerCase(), new TimezoneInfo("Asia/Ashkhabad", "AS", "Asia", "TM", "Turkmenistan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Samarkand".toLowerCase(), new TimezoneInfo("Asia/Samarkand", "AS", "Asia", "UZ", "Uzbekistan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Tashkent".toLowerCase(), new TimezoneInfo("Asia/Tashkent", "AS", "Asia", "UZ", "Uzbekistan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Aqtau".toLowerCase(), new TimezoneInfo("Asia/Aqtau", "AS", "Asia", "KZ", "Kazakhstan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Aqtobe".toLowerCase(), new TimezoneInfo("Asia/Aqtobe", "AS", "Asia", "KZ", "Kazakhstan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Atyrau".toLowerCase(), new TimezoneInfo("Asia/Atyrau", "AS", "Asia", "KZ", "Kazakhstan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Oral".toLowerCase(), new TimezoneInfo("Asia/Oral", "AS", "Asia", "KZ", "Kazakhstan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Qyzylorda".toLowerCase(), new TimezoneInfo("Asia/Qyzylorda", "AS", "Asia", "KZ", "Kazakhstan", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Yekaterinburg".toLowerCase(), new TimezoneInfo("Asia/Yekaterinburg", "EU", "Europe", "RU", "Russia", c.COLLECT_MODE_FINANCE));
        this.countries.put("Asia/Colombo".toLowerCase(), new TimezoneInfo("Asia/Colombo", "AS", "Asia", "LK", "Sri Lanka", c.COLLECT_MODE_TIKTOKLITE));
        this.countries.put("Asia/Kolkata".toLowerCase(), new TimezoneInfo("Asia/Kolkata", "AS", "Asia", "IN", "India", c.COLLECT_MODE_TIKTOKLITE));
        this.countries.put("Asia/Calcutta".toLowerCase(), new TimezoneInfo("Asia/Calcutta", "AS", "Asia", "IN", "India", c.COLLECT_MODE_TIKTOKLITE));
        this.countries.put("Asia/Kathmandu".toLowerCase(), new TimezoneInfo("Asia/Kathmandu", "AS", "Asia", "NP", "Nepal", 345));
        this.countries.put("Asia/Katmandu".toLowerCase(), new TimezoneInfo("Asia/Katmandu", "AS", "Asia", "NP", "Nepal", 345));
        this.countries.put("Asia/Dhaka".toLowerCase(), new TimezoneInfo("Asia/Dhaka", "AS", "Asia", "BD", "Bangladesh", 360));
        this.countries.put("Asia/Dacca".toLowerCase(), new TimezoneInfo("Asia/Dacca", "AS", "Asia", "BD", "Bangladesh", 360));
        this.countries.put("Asia/Thimphu".toLowerCase(), new TimezoneInfo("Asia/Thimphu", "AS", "Asia", "BT", "Bhutan", 360));
        this.countries.put("Asia/Thimbu".toLowerCase(), new TimezoneInfo("Asia/Thimbu", "AS", "Asia", "BT", "Bhutan", 360));
        this.countries.put("Asia/Urumqi".toLowerCase(), new TimezoneInfo("Asia/Urumqi", "AS", "Asia", "CN", "China", 360));
        this.countries.put("Asia/Kashgar".toLowerCase(), new TimezoneInfo("Asia/Kashgar", "AS", "Asia", "CN", "China", 360));
        this.countries.put("Asia/Almaty".toLowerCase(), new TimezoneInfo("Asia/Almaty", "AS", "Asia", "KZ", "Kazakhstan", 360));
        this.countries.put("Asia/Qostanay".toLowerCase(), new TimezoneInfo("Asia/Qostanay", "AS", "Asia", "KZ", "Kazakhstan", 360));
        this.countries.put("Indian/Chagos".toLowerCase(), new TimezoneInfo("Indian/Chagos", "AS", "Asia", "IO", "British Indian Ocean Territory", 360));
        this.countries.put("Asia/Bishkek".toLowerCase(), new TimezoneInfo("Asia/Bishkek", "AS", "Asia", "KG", "Kyrgyzstan", 360));
        this.countries.put("Asia/Omsk".toLowerCase(), new TimezoneInfo("Asia/Omsk", "EU", "Europe", "RU", "Russia", 360));
        this.countries.put("Antarctica/Vostok".toLowerCase(), new TimezoneInfo("Antarctica/Vostok", "AN", "Antarctica", "AQ", "Antarctica", 360));
        this.countries.put("Indian/Cocos".toLowerCase(), new TimezoneInfo("Indian/Cocos", "AS", "Asia", "CC", "Cocos Islands", 390));
        this.countries.put("Asia/Yangon".toLowerCase(), new TimezoneInfo("Asia/Yangon", "AS", "Asia", "MM", "Myanmar", 390));
        this.countries.put("Asia/Rangoon".toLowerCase(), new TimezoneInfo("Asia/Rangoon", "AS", "Asia", "MM", "Myanmar", 390));
        this.countries.put("Indian/Christmas".toLowerCase(), new TimezoneInfo("Indian/Christmas", "OC", "Oceania", "CX", "Christmas Island", 420));
        this.countries.put("Antarctica/Davis".toLowerCase(), new TimezoneInfo("Antarctica/Davis", "AN", "Antarctica", "AQ", "Antarctica", 420));
        this.countries.put("Asia/Hovd".toLowerCase(), new TimezoneInfo("Asia/Hovd", "AS", "Asia", "MN", "Mongolia", 420));
        this.countries.put("Asia/Bangkok".toLowerCase(), new TimezoneInfo("Asia/Bangkok", "AS", "Asia", "TH", "Thailand", 420));
        this.countries.put("Asia/Ho_Chi_Minh".toLowerCase(), new TimezoneInfo("Asia/Ho_Chi_Minh", "AS", "Asia", "VN", "Vietnam", 420));
        this.countries.put("Asia/Saigon".toLowerCase(), new TimezoneInfo("Asia/Saigon", "AS", "Asia", "VN", "Vietnam", 420));
        this.countries.put("Asia/Phnom_Penh".toLowerCase(), new TimezoneInfo("Asia/Phnom_Penh", "AS", "Asia", "KH", "Cambodia", 420));
        this.countries.put("Asia/Vientiane".toLowerCase(), new TimezoneInfo("Asia/Vientiane", "AS", "Asia", "LA", "Laos", 420));
        this.countries.put("Asia/Barnaul".toLowerCase(), new TimezoneInfo("Asia/Barnaul", "EU", "Europe", "RU", "Russia", 420));
        this.countries.put("Asia/Krasnoyarsk".toLowerCase(), new TimezoneInfo("Asia/Krasnoyarsk", "EU", "Europe", "RU", "Russia", 420));
        this.countries.put("Asia/Novokuznetsk".toLowerCase(), new TimezoneInfo("Asia/Novokuznetsk", "EU", "Europe", "RU", "Russia", 420));
        this.countries.put("Asia/Novosibirsk".toLowerCase(), new TimezoneInfo("Asia/Novosibirsk", "EU", "Europe", "RU", "Russia", 420));
        this.countries.put("Asia/Tomsk".toLowerCase(), new TimezoneInfo("Asia/Tomsk", "EU", "Europe", "RU", "Russia", 420));
        this.countries.put("Asia/Jakarta".toLowerCase(), new TimezoneInfo("Asia/Jakarta", "AS", "Asia", "ID", "Indonesia", 420));
        this.countries.put("Asia/Pontianak".toLowerCase(), new TimezoneInfo("Asia/Pontianak", "AS", "Asia", "ID", "Indonesia", 420));
        this.countries.put("Australia/Perth".toLowerCase(), new TimezoneInfo("Australia/Perth", "OC", "Oceania", "AU", "Australia", 480));
        this.countries.put("Australia/West".toLowerCase(), new TimezoneInfo("Australia/West", "OC", "Oceania", "AU", "Australia", 480));
        this.countries.put("Asia/Brunei".toLowerCase(), new TimezoneInfo("Asia/Brunei", "AS", "Asia", "BN", "Brunei", 480));
        this.countries.put("Asia/Makassar".toLowerCase(), new TimezoneInfo("Asia/Makassar", "AS", "Asia", "ID", "Indonesia", 480));
        this.countries.put("Asia/Ujung_Pandang".toLowerCase(), new TimezoneInfo("Asia/Ujung_Pandang", "AS", "Asia", "ID", "Indonesia", 480));
        this.countries.put("Asia/Macau".toLowerCase(), new TimezoneInfo("Asia/Macau", "AS", "Asia", "MO", "Macao", 480));
        this.countries.put("Asia/Macao".toLowerCase(), new TimezoneInfo("Asia/Macao", "AS", "Asia", "MO", "Macao", 480));
        this.countries.put("Asia/Shanghai".toLowerCase(), new TimezoneInfo("Asia/Shanghai", "AS", "Asia", "CN", "China", 480));
        this.countries.put("Asia/Chongqing".toLowerCase(), new TimezoneInfo("Asia/Chongqing", "AS", "Asia", "CN", "China", 480));
        this.countries.put("Asia/Chungking".toLowerCase(), new TimezoneInfo("Asia/Chungking", "AS", "Asia", "CN", "China", 480));
        this.countries.put("Asia/Harbin".toLowerCase(), new TimezoneInfo("Asia/Harbin", "AS", "Asia", "CN", "China", 480));
        this.countries.put("PRC".toLowerCase(), new TimezoneInfo("PRC", "AS", "Asia", "CN", "China", 480));
        this.countries.put("Asia/Hong_Kong".toLowerCase(), new TimezoneInfo("Asia/Hong_Kong", "AS", "Asia", "HK", "Hong Kong", 480));
        this.countries.put("Hongkong".toLowerCase(), new TimezoneInfo("Hongkong", "AS", "Asia", "HK", "Hong Kong", 480));
        this.countries.put("Asia/Irkutsk".toLowerCase(), new TimezoneInfo("Asia/Irkutsk", "EU", "Europe", "RU", "Russia", 480));
        this.countries.put("Asia/Kuala_Lumpur".toLowerCase(), new TimezoneInfo("Asia/Kuala_Lumpur", "AS", "Asia", "MY", "Malaysia", 480));
        this.countries.put("Asia/Kuching".toLowerCase(), new TimezoneInfo("Asia/Kuching", "AS", "Asia", "MY", "Malaysia", 480));
        this.countries.put("Asia/Manila".toLowerCase(), new TimezoneInfo("Asia/Manila", "AS", "Asia", "PH", "Philippines", 480));
        this.countries.put("Asia/Singapore".toLowerCase(), new TimezoneInfo("Asia/Singapore", "AS", "Asia", "SG", "Singapore", 480));
        this.countries.put("Singapore".toLowerCase(), new TimezoneInfo("Singapore", "AS", "Asia", "SG", "Singapore", 480));
        this.countries.put("Asia/Taipei".toLowerCase(), new TimezoneInfo("Asia/Taipei", "AS", "Asia", "TW", "Taiwan", 480));
        this.countries.put("ROC".toLowerCase(), new TimezoneInfo("ROC", "AS", "Asia", "TW", "Taiwan", 480));
        this.countries.put("Asia/Choibalsan".toLowerCase(), new TimezoneInfo("Asia/Choibalsan", "AS", "Asia", "MN", "Mongolia", 480));
        this.countries.put("Asia/Ulaanbaatar".toLowerCase(), new TimezoneInfo("Asia/Ulaanbaatar", "AS", "Asia", "MN", "Mongolia", 480));
        this.countries.put("Asia/Ulan_Bator".toLowerCase(), new TimezoneInfo("Asia/Ulan_Bator", "AS", "Asia", "MN", "Mongolia", 480));
        this.countries.put("Australia/Eucla".toLowerCase(), new TimezoneInfo("Australia/Eucla", "OC", "Oceania", "AU", "Australia", IronSourceError.ERROR_AD_UNIT_CAPPED));
        this.countries.put("Asia/Dili".toLowerCase(), new TimezoneInfo("Asia/Dili", "OC", "Oceania", "TL", "Timor Leste", 540));
        this.countries.put("Asia/Jayapura".toLowerCase(), new TimezoneInfo("Asia/Jayapura", "AS", "Asia", "ID", "Indonesia", 540));
        this.countries.put("Asia/Tokyo".toLowerCase(), new TimezoneInfo("Asia/Tokyo", "AS", "Asia", "JP", "Japan", 540));
        this.countries.put("Japan".toLowerCase(), new TimezoneInfo("Japan", "AS", "Asia", "JP", "Japan", 540));
        this.countries.put("Asia/Pyongyang".toLowerCase(), new TimezoneInfo("Asia/Pyongyang", "AS", "Asia", "KP", "North Korea", 540));
        this.countries.put("Asia/Seoul".toLowerCase(), new TimezoneInfo("Asia/Seoul", "AS", "Asia", "KR", "South Korea", 540));
        this.countries.put("ROK".toLowerCase(), new TimezoneInfo("ROK", "AS", "Asia", "KR", "South Korea", 540));
        this.countries.put("Pacific/Palau".toLowerCase(), new TimezoneInfo("Pacific/Palau", "OC", "Oceania", "PW", "Palau", 540));
        this.countries.put("Asia/Chita".toLowerCase(), new TimezoneInfo("Asia/Chita", "EU", "Europe", "RU", "Russia", 540));
        this.countries.put("Asia/Khandyga".toLowerCase(), new TimezoneInfo("Asia/Khandyga", "EU", "Europe", "RU", "Russia", 540));
        this.countries.put("Asia/Yakutsk".toLowerCase(), new TimezoneInfo("Asia/Yakutsk", "EU", "Europe", "RU", "Russia", 540));
        this.countries.put("Australia/Adelaide".toLowerCase(), new TimezoneInfo("Australia/Adelaide", "OC", "Oceania", "AU", "Australia", 570));
        this.countries.put("Australia/Broken_Hill".toLowerCase(), new TimezoneInfo("Australia/Broken_Hill", "OC", "Oceania", "AU", "Australia", 570));
        this.countries.put("Australia/South".toLowerCase(), new TimezoneInfo("Australia/South", "OC", "Oceania", "AU", "Australia", 570));
        this.countries.put("Australia/Yancowinna".toLowerCase(), new TimezoneInfo("Australia/Yancowinna", "OC", "Oceania", "AU", "Australia", 570));
        this.countries.put("Australia/Darwin".toLowerCase(), new TimezoneInfo("Australia/Darwin", "OC", "Oceania", "AU", "Australia", 570));
        this.countries.put("Australia/North".toLowerCase(), new TimezoneInfo("Australia/North", "OC", "Oceania", "AU", "Australia", 570));
        this.countries.put("Australia/Brisbane".toLowerCase(), new TimezoneInfo("Australia/Brisbane", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Lindeman".toLowerCase(), new TimezoneInfo("Australia/Lindeman", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Queensland".toLowerCase(), new TimezoneInfo("Australia/Queensland", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Antarctica/Macquarie".toLowerCase(), new TimezoneInfo("Antarctica/Macquarie", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Hobart".toLowerCase(), new TimezoneInfo("Australia/Hobart", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Melbourne".toLowerCase(), new TimezoneInfo("Australia/Melbourne", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Sydney".toLowerCase(), new TimezoneInfo("Australia/Sydney", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Currie".toLowerCase(), new TimezoneInfo("Australia/Currie", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Tasmania".toLowerCase(), new TimezoneInfo("Australia/Tasmania", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Victoria".toLowerCase(), new TimezoneInfo("Australia/Victoria", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/ACT".toLowerCase(), new TimezoneInfo("Australia/ACT", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/Canberra".toLowerCase(), new TimezoneInfo("Australia/Canberra", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Australia/NSW".toLowerCase(), new TimezoneInfo("Australia/NSW", "OC", "Oceania", "AU", "Australia", 600));
        this.countries.put("Pacific/Guam".toLowerCase(), new TimezoneInfo("Pacific/Guam", "OC", "Oceania", "GU", "Guam", 600));
        this.countries.put("Pacific/Saipan".toLowerCase(), new TimezoneInfo("Pacific/Saipan", "OC", "Oceania", "MP", "Northern Mariana Islands", 600));
        this.countries.put("Pacific/Chuuk".toLowerCase(), new TimezoneInfo("Pacific/Chuuk", "OC", "Oceania", "FM", "Micronesia", 600));
        this.countries.put("Pacific/Truk".toLowerCase(), new TimezoneInfo("Pacific/Truk", "OC", "Oceania", RequestConfiguration.MAX_AD_CONTENT_RATING_PG, "Papua New Guinea", 600));
        this.countries.put("Pacific/Yap".toLowerCase(), new TimezoneInfo("Pacific/Yap", "OC", "Oceania", RequestConfiguration.MAX_AD_CONTENT_RATING_PG, "Papua New Guinea", 600));
        this.countries.put("Antarctica/DumontDUrville".toLowerCase(), new TimezoneInfo("Antarctica/DumontDUrville", "AN", "Antarctica", "AQ", "Antarctica", 600));
        this.countries.put("Pacific/Port_Moresby".toLowerCase(), new TimezoneInfo("Pacific/Port_Moresby", "OC", "Oceania", RequestConfiguration.MAX_AD_CONTENT_RATING_PG, "Papua New Guinea", 600));
        this.countries.put("Asia/Ust-Nera".toLowerCase(), new TimezoneInfo("Asia/Ust-Nera", "EU", "Europe", "RU", "Russia", 600));
        this.countries.put("Asia/Vladivostok".toLowerCase(), new TimezoneInfo("Asia/Vladivostok", "EU", "Europe", "RU", "Russia", 600));
        this.countries.put("Australia/Lord_Howe".toLowerCase(), new TimezoneInfo("Australia/Lord_Howe", "OC", "Oceania", "AU", "Australia", 630));
        this.countries.put("Australia/LHI".toLowerCase(), new TimezoneInfo("Australia/LHI", "OC", "Oceania", "AU", "Australia", 630));
        this.countries.put("Pacific/Bougainville".toLowerCase(), new TimezoneInfo("Pacific/Bougainville", "OC", "Oceania", RequestConfiguration.MAX_AD_CONTENT_RATING_PG, "Papua New Guinea", 660));
        this.countries.put("Antarctica/Casey".toLowerCase(), new TimezoneInfo("Antarctica/Casey", "AN", "Antarctica", "AQ", "Antarctica", 660));
        this.countries.put("Pacific/Kosrae".toLowerCase(), new TimezoneInfo("Pacific/Kosrae", "OC", "Oceania", "FM", "Micronesia", 660));
        this.countries.put("Pacific/Pohnpei".toLowerCase(), new TimezoneInfo("Pacific/Pohnpei", "OC", "Oceania", "FM", "Micronesia", 660));
        this.countries.put("Pacific/Noumea".toLowerCase(), new TimezoneInfo("Pacific/Noumea", "OC", "Oceania", "NC", "New Caledonia", 660));
        this.countries.put("Pacific/Norfolk".toLowerCase(), new TimezoneInfo("Pacific/Norfolk", "OC", "Oceania", "NF", "Norfolk Island", 660));
        this.countries.put("Asia/Magadan".toLowerCase(), new TimezoneInfo("Asia/Magadan", "EU", "Europe", "RU", "Russia", 660));
        this.countries.put("Asia/Sakhalin".toLowerCase(), new TimezoneInfo("Asia/Sakhalin", "EU", "Europe", "RU", "Russia", 660));
        this.countries.put("Asia/Srednekolymsk".toLowerCase(), new TimezoneInfo("Asia/Srednekolymsk", "EU", "Europe", "RU", "Russia", 660));
        this.countries.put("Pacific/Guadalcanal".toLowerCase(), new TimezoneInfo("Pacific/Guadalcanal", "OC", "Oceania", "SB", "Solomon Islands", 660));
        this.countries.put("Pacific/Ponape".toLowerCase(), new TimezoneInfo("Pacific/Ponape", "OC", "Oceania", "SB", "Solomon Islands", 660));
        this.countries.put("Pacific/Efate".toLowerCase(), new TimezoneInfo("Pacific/Efate", "OC", "Oceania", "VU", "Vanuatu", 660));
        this.countries.put("Pacific/Fiji".toLowerCase(), new TimezoneInfo("Pacific/Fiji", "OC", "Oceania", "FJ", "Fiji", 720));
        this.countries.put("Pacific/Tarawa".toLowerCase(), new TimezoneInfo("Pacific/Tarawa", "OC", "Oceania", "KI", "Kiribati", 720));
        this.countries.put("Pacific/Kwajalein".toLowerCase(), new TimezoneInfo("Pacific/Kwajalein", "OC", "Oceania", "MH", "Marshall Islands", 720));
        this.countries.put("Pacific/Majuro".toLowerCase(), new TimezoneInfo("Pacific/Majuro", "OC", "Oceania", "MH", "Marshall Islands", 720));
        this.countries.put("Kwajalein".toLowerCase(), new TimezoneInfo("Kwajalein", "OC", "Oceania", "MH", "Marshall Islands", 720));
        this.countries.put("Pacific/Nauru".toLowerCase(), new TimezoneInfo("Pacific/Nauru", "OC", "Oceania", "NR", "Nauru", 720));
        this.countries.put("Pacific/Auckland".toLowerCase(), new TimezoneInfo("Pacific/Auckland", "OC", "Oceania", "NZ", "New Zealand", 720));
        this.countries.put("Antarctica/South_Pole".toLowerCase(), new TimezoneInfo("Antarctica/South_Pole", "OC", "Oceania", "NZ", "New Zealand", 720));
        this.countries.put("NZ".toLowerCase(), new TimezoneInfo("NZ", "OC", "Oceania", "NZ", "New Zealand", 720));
        this.countries.put("Antarctica/McMurdo".toLowerCase(), new TimezoneInfo("Antarctica/McMurdo", "AN", "Antarctica", "AQ", "Antarctica", 720));
        this.countries.put("Asia/Anadyr".toLowerCase(), new TimezoneInfo("Asia/Anadyr", "EU", "Europe", "RU", "Russia", 720));
        this.countries.put("Asia/Kamchatka".toLowerCase(), new TimezoneInfo("Asia/Kamchatka", "EU", "Europe", "RU", "Russia", 720));
        this.countries.put("Pacific/Funafuti".toLowerCase(), new TimezoneInfo("Pacific/Funafuti", "OC", "Oceania", "TV", "Tuvalu", 720));
        this.countries.put("Pacific/Wake".toLowerCase(), new TimezoneInfo("Pacific/Wake", "OC", "Oceania", "UM", "United States Minor Outlying Islands", 720));
        this.countries.put("Pacific/Wallis".toLowerCase(), new TimezoneInfo("Pacific/Wallis", "OC", "Oceania", "WF", "Wallis and Futuna", 720));
        this.countries.put("Pacific/Chatham".toLowerCase(), new TimezoneInfo("Pacific/Chatham", "OC", "Oceania", "NZ", "New Zealand", 765));
        this.countries.put("NZ-CHAT".toLowerCase(), new TimezoneInfo("NZ-CHAT", "OC", "Oceania", "NZ", "New Zealand", 765));
        this.countries.put("Pacific/Apia".toLowerCase(), new TimezoneInfo("Pacific/Apia", "OC", "Oceania", "WS", "Samoa", 780));
        this.countries.put("Pacific/Fakaofo".toLowerCase(), new TimezoneInfo("Pacific/Fakaofo", "OC", "Oceania", "TK", "Tokelau", 780));
        this.countries.put("Pacific/Tongatapu".toLowerCase(), new TimezoneInfo("Pacific/Tongatapu", "OC", "Oceania", "TO", "Tonga", 780));
        this.countries.put("Pacific/Kiritimati".toLowerCase(), new TimezoneInfo("Pacific/Kiritimati", "OC", "Oceania", "KI", "Kiribati", 840));
    }

    public TimezoneInfo getDeviceTimezoneInfo() {
        if (this.countries == null) {
            initCountries();
        }
        String str = this.zoneId;
        if (str != null && this.countries.containsKey(str.toLowerCase())) {
            return this.countries.get(this.zoneId.toLowerCase());
        }
        return null;
    }
}
